common_packages:
  RedHat:
    8:
      - jq
      - platform-python-setuptools
      - python3-pip
      - kubectl
      - python3-kubernetes
    9:
      - jq
      - python-setuptools
      - python3-pip
      - kubectl
      - python3-kubernetes
  Debian:
    24:
      - jq
      - python3-pip
      - python3-setuptools
      - kubectl
      - python3-kubernetes

azure_gpg_keys:
  8:
    - https://rpm.releases.hashicorp.com/gpg
    - https://packages.microsoft.com/keys/microsoft.asc
  9:
    - https://rpm.releases.hashicorp.com/gpg
    - https://packages.microsoft.com/keys/microsoft.asc

azure_microsoft_repo:
  8:
    - https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm
  9:
    - https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm

azure_pip_packages:
  8:
    - azure-cli-core
  9:
    - azure-cli-core

azure_rpm_packages:
  8:
    - azure-cli
    - yum-utils
    - terraform
  9:
    - azure-cli
    - yum-utils
    - terraform

gcloud_gpg_keys:
  8:
    - https://rpm.releases.hashicorp.com/gpg
  9:
    - https://rpm.releases.hashicorp.com/gpg

gcloud_rpm_packages:
  8:
    - google-cloud-sdk-gke-gcloud-auth-plugin
    - yum-utils
    - terraform
  9:
    - google-cloud-sdk-gke-gcloud-auth-plugin
    - yum-utils
    - terraform

gcloud_pip_packages:
  8:
    - jmespath
  9:
    - jmespath

aws_rpm_packages:
  8:
    - yum-utils
    - terraform
  9:
    - yum-utils
    - terraform

aws_pip_packages:
  8:
    - boto3
    - botocore
    - jmespath
  9:
    - boto3
    - botocore
    - jmespath