- name: Retrieve the current time in order to timestamp files
  ansible.builtin.setup:
    gather_subset:
     - date_time

- name: Generate manifest to install Ledger k8s object with timestamp attached, for purposes of deletion later
  ansible.builtin.template:
    src: ledger_deployment_gke.yaml
    dest: "{{ tmp_dir }}/ledger_deployment_gke.yaml.{{ ansible_date_time.iso8601_basic_short }}"

- name: Generate manifest for the Ledger registry secret with timestamp, for purposes of deletion later
  when: LEDGER_REGISTRY.BASE is defined
  ansible.builtin.template:
    src: ledger_deployment_registry_secret.yaml
    dest: "{{ tmp_dir }}/ledger_deployment_registry_secret.yaml.{{ ansible_date_time.iso8601_basic_short }}"

- name: Apply ledger registry secret (if needed) manifest for {{ k8s_platform }}
  when: LEDGER_REGISTRY.BASE is defined
  kubernetes.core.k8s:
    state: present
    namespace: "{{ LEDGER_NAMESPACE }}"
    definition: "{{ lookup('template', 'templates/ledger_deployment_registry_secret.yaml') | from_yaml }}"
    verify_ssl: false

- name: "Apply ledger manifest for {{ k8s_platform }}"
  kubernetes.core.k8s:
    state: present
    namespace: "{{ LEDGER_NAMESPACE }}"
    definition: "{{ lookup('template', 'templates/ledger_deployment_gke.yaml') | from_yaml_all }}"
    verify_ssl: false

- name: Wait for Ledger web Deployment to complete setting up
  kubernetes.core.k8s_info:
    kind: Deployment
    wait: yes
    name: web
    namespace: "{{ LEDGER_NAMESPACE }}"
    wait_sleep: 10
    wait_timeout: 360
    verify_ssl: false

- name: Wait for Ledger parser Service to be up
  kubernetes.core.k8s_info:
    kind: Service
    wait: yes
    name: parser
    namespace: "{{ LEDGER_NAMESPACE }}"
    wait_sleep: 10
    wait_timeout: 360
    verify_ssl: false
  register: parser_svc
      
- ansible.builtin.debug:
    var: parser_svc.resources[0].spec.ports[0].port

- name: Retrieve the ledger-web-ingress Ingress object
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Ingress
    name: ledger-web-ingress
    namespace: "{{ LEDGER_NAMESPACE }}"
  register: ledger_ingress
  until:
    - ledger_ingress.resources[0].status.loadBalancer.ingress[0].ip is defined
    - ledger_ingress.resources[0].spec.rules[0].host is defined
  retries: 20

- ansible.builtin.debug: 
    var: ledger_ingress.resources[0].status.loadBalancer.ingress[0].ip

- ansible.builtin.debug: 
    var: ledger_ingress.resources[0].spec.rules[0].host

- name: Check if Google Cloud DNS A record exists
  ansible.builtin.command: >
    gcloud dns record-sets list --zone={{ GOOGLE_DNS_MANAGED_ZONE }} --name={{ LEDGER_HOSTNAME }} --type=A --format=json
  register: dns_records
  when: USE_GOOGLE_DNS

- name: Parse DNS records to check for any existing record
  ansible.builtin.set_fact:
    record_exists: "{{ dns_records.stdout | from_json | json_query('[?type==`A`]') | length > 0 }}"
  when: USE_GOOGLE_DNS

- name: Conditionally manage the Google Cloud DNS record based on existence
  block:
    - name: Remove existing Google Cloud DNS A record if it exists
      block:
        - name: Start DNS transaction
          ansible.builtin.command: gcloud dns record-sets transaction start --zone={{ GOOGLE_DNS_MANAGED_ZONE }}

        - name: Remove Google Cloud DNS A record
          ansible.builtin.command: >
            gcloud dns record-sets transaction remove --zone={{ GOOGLE_DNS_MANAGED_ZONE }}
            --name={{ LEDGER_HOSTNAME }} --type=A
            --ttl={{ dns_records.stdout | from_json | json_query('[?type==`A`].ttl | [0]') }}
            {{ dns_records.stdout | from_json | json_query('[?type==`A`].rrdatas[] | [0]') }}

        - name: Execute Google Cloud DNS transaction
          ansible.builtin.command: gcloud dns record-sets transaction execute --zone={{ GOOGLE_DNS_MANAGED_ZONE }}
      when: record_exists

    - name: Add Google Cloud DNS A record
      block:
        - name: Start Google Cloud DNS transaction
          ansible.builtin.command: gcloud dns record-sets transaction start --zone={{ GOOGLE_DNS_MANAGED_ZONE }}

        - name: Add Google Cloud DNS A record
          ansible.builtin.command: >
            gcloud dns record-sets transaction add --zone={{ GOOGLE_DNS_MANAGED_ZONE }}
            --name={{ LEDGER_HOSTNAME }} --type=A
            --ttl=600 {{ ledger_ingress.resources[0].status.loadBalancer.ingress[0].ip }}

        - name: Execute Google Cloud DNS transaction
          ansible.builtin.command: gcloud dns record-sets transaction execute --zone={{ GOOGLE_DNS_MANAGED_ZONE }}
  when: USE_GOOGLE_DNS

- name: Indicate Instructions for non-Google DNS Domain Management
  ansible.builtin.debug: 
    msg: "Please manually create a DNS A record for {{ LEDGER_HOSTNAME }} in your DNS Record Manager of choice, mapping to {{ ledger_ingress.resources[0].status.loadBalancer.ingress[0].ip }}"
  when: not USE_GOOGLE_DNS

- name: Set the Ledger URL
  ansible.builtin.set_fact:
      ledger_ip: "{{ LEDGER_HOSTNAME }}"
      ledger_port: "{{  '443' if k8s_lb_protocol == 'https' else '80' }}"
      ledger_parser_ip: "{{ parser_svc.resources[0].spec.clusterIP }}"
      ledger_parser_port: "{{ parser_svc.resources[0].spec.ports[0].port }}"

- ansible.builtin.debug:
    msg: "The Ledger endpoint is {{ k8s_lb_protocol }}://{{ ledger_ip }}"

- name: Wait until Ledger endpoint is Up
  ansible.builtin.uri:
    url: "{{ k8s_lb_protocol }}://{{ ledger_ip }}"
    return_content: yes
    validate_certs: false
    status_code:
      - 200
  until: uri_output.status == 200
  retries: 200
  delay: 10
  register: uri_output

- ansible.builtin.debug:
    msg: "Ledger webpage is up"

- name: Set the Ascender URL and Credentials for HTTPS
  ansible.builtin.set_fact:
    ascender_username: "{{ ASCENDER_ADMIN_USER }}"
    ascender_ip: "{{ ASCENDER_HOSTNAME }}"
    ascender_port: 443
    ascender_password: "{{ ASCENDER_ADMIN_PASSWORD }}"
  when: k8s_lb_protocol == "https"

- name: Set the Ascender URL and Credentials for HTTP
  ansible.builtin.set_fact:
      ascender_username: "{{ ASCENDER_ADMIN_USER }}"
      ascender_ip: "{{ ASCENDER_HOSTNAME }}"
      ascender_port: 80
  when: k8s_lb_protocol == "http"

- ansible.builtin.debug:
    msg: "The Ascender API endpoint is {{ k8s_lb_protocol }}://{{ ascender_ip }}:{{ ascender_port }}/api/v2/ping/"

- name: Wait until Ascender API is Up
  ansible.builtin.uri:
    url: "{{ k8s_lb_protocol }}://{{ ascender_ip }}:{{ ascender_port }}/api/v2/ping/"
    return_content: yes
    validate_certs: false
    status_code:
      - 200
  until: uri_output.status == 200
  retries: 60
  delay: 10
  register: uri_output

- ansible.builtin.debug:
    msg: "Ascender API is up"

- when: LEDGER_REGISTRY.BASE is defined and LEDGER_REGISTRY.BASE != ""
  block:

    - name: Check Ledger Token
      ansible.builtin.uri:
        url: "{{ k8s_lb_protocol }}://{{ ledger_ip }}/api/v1/settings/"
        user: admin
        password: "{{ LEDGER_ADMIN_PASSWORD }}"
        force_basic_auth: true
        return_content: yes
        validate_certs: false
        status_code:
          - 200
      until: uri_output.status == 200
      retries: 60
      delay: 10
      register: ledger_settings

    - name: Regenerate Token if blank
      ansible.builtin.uri:
        url: "{{ k8s_lb_protocol }}://{{ ledger_ip }}/api/v1/settings/?regenerate_auth_token=1"
        user: admin
        password: "{{ LEDGER_ADMIN_PASSWORD }}"
        force_basic_auth: true
        return_content: yes
        validate_certs: false
        status_code:
          - 200
      until: uri_output.status == 200
      retries: 60
      delay: 10
      register: ledger_settings2
      when: ledger_settings.json.auth_token is undefined or ledger_settings.json.auth_token == ""

    - name: Get Ledger Token Again (in case of regeneration)
      ansible.builtin.uri:
        url: "{{ k8s_lb_protocol }}://{{ ledger_ip }}/api/v1/settings/"
        user: admin
        password: "{{ LEDGER_ADMIN_PASSWORD }}"
        force_basic_auth: true
        return_content: yes
        validate_certs: false
        status_code:
          - 200
      until: uri_output.status == 200
      retries: 60
      delay: 10
      register: ledger_settings

    - ansible.builtin.debug:
        var: ledger_settings.json.auth_token

    - name: Enable Require Token
      ansible.builtin.uri:
        url: "{{ k8s_lb_protocol }}://{{ ledger_ip }}/api/v1/settings/"
        user: admin
        password: "{{ LEDGER_ADMIN_PASSWORD }}"
        force_basic_auth: true
        method: POST
        body_format: json
        body: '{ "require_auth_token": 1, "base_url": "{{ k8s_lb_protocol }}://{{ ledger_ip }}" }'
        return_content: yes
        validate_certs: false
        status_code:
          - 200
      until: uri_output.status == 200
      retries: 60
      delay: 10
      when:
        - ledger_settings.json.auth_token is defined
        - ledger_settings.json.require_auth_token is undefined or ledger_settings.json.require_auth_token == 0
      register: test

- name: Set all the logging parameters
  awx.awx.settings:
    controller_host: "{{ k8s_lb_protocol }}://{{ ascender_ip }}:{{ ascender_port }}"
    controller_username: "{{ ASCENDER_ADMIN_USER }}"
    controller_password: "{{ ASCENDER_ADMIN_PASSWORD }}"
    validate_certs: false
    settings:
      LOG_AGGREGATOR_HOST: "{{ k8s_lb_protocol }}://{{ ledger_parser_ip }}"
      LOG_AGGREGATOR_PORT: "{{ ledger_parser_port }}"
      LOG_AGGREGATOR_TYPE: ledger
      LOG_AGGREGATOR_ENABLED: true
      LOG_AGGREGATOR_VERIFY_CERT: false
      LOG_AGGREGATOR_LEVEL: INFO
      LOG_AGGREGATOR_PASSWORD: "{{ ledger_settings.json.auth_token | default(omit, true) }}"
      TOWER_URL_BASE: "{{ k8s_lb_protocol }}://{{ ascender_ip }}:{{ ascender_port }}"