# Copyright (c) 2025, Ctrl IQ, Inc. All rights reserved.

- hosts: localhost
  gather_facts: no
  become: false

  vars_files:
    - ["../custom.config.yml", "../default.config.yml"]

  environment:
    K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/config"
    NAMESPACE: "{{ ASCENDER_NAMESPACE }}"
    PATH: "/usr/local/bin:{{ lookup('env', 'PATH') }}" #required as the aws cli lives at /usr/local/bin/aws

  tasks: 

    - name: "Run ascender_react role for {{ k8s_platform }}"
      ansible.builtin.include_role:
        name: ascender_react
        tasks_from: "react_install_{{ k8s_platform }}"

    - ansible.builtin.debug:
        msg: "React install complete."