apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ ledger_service_account_name }}
  namespace: {{ LEDGER_NAMESPACE }}
---
apiVersion: v1
stringData:
  admin-password: {{ LEDGER_ADMIN_PASSWORD }}
kind: Secret
metadata:
  labels:
    io.kompose.service: admin-password
  name: admin-password
  namespace: {{ LEDGER_NAMESPACE }}
type: Opaque
---
apiVersion: v1
stringData:
  config.json: |
    {
      "db_host": "{{ LEDGER_DB_HOST }}",
      "db_port": "{{ LEDGER_DB_PORT }}",
      "db_name": "{{ LEDGER_DB_NAME }}",
      "db_username": "{{ LEDGER_DB_USERNAME }}",
      "db_password": "{{ LEDGER_DB_PASSWORD }}"
    }
kind: Secret
metadata:
  labels:
    io.kompose.service: db-settings
  name: db-settings
  namespace: {{ LEDGER_NAMESPACE }}
type: Opaque
{% if 'https' == k8s_lb_protocol  %}
---
apiVersion: v1
data:
  tls.crt: {{ lookup('ansible.builtin.file', tls_crt_path) | b64encode }}
  tls.key: {{ lookup('ansible.builtin.file', tls_key_path) | b64encode }}
kind: Secret
metadata:
  name: ascender-tls-secret
  namespace: {{ LEDGER_NAMESPACE }}
type: kubernetes.io/tls
{% endif %}
---
apiVersion: v1
stringData:
  db-ledger-password: {{ LEDGER_DB_PASSWORD }}
kind: Secret
metadata:
  labels:
    io.kompose.service: db-ledger-password
  name: db-ledger-password
  namespace: {{ LEDGER_NAMESPACE }}
type: Opaque
{% if LEDGER_DB_HOST == "db" %}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: db
  name: db
  namespace: {{ LEDGER_NAMESPACE }}
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: db
{% endif %}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: parser
  name: parser
  namespace: {{ LEDGER_NAMESPACE }}
spec:
  type: ClusterIP
  ports:
  - name: parser-port
    port: 5000
    targetPort: 5000
  selector:
    io.kompose.service: parser
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: web-svc
  name: web-svc
  namespace: {{ LEDGER_NAMESPACE }}
spec:
  type: ClusterIP
  ports:
  - name: web-port
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: web
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web-route
  namespace: {{ LEDGER_NAMESPACE }}
spec:
  host: {{ LEDGER_HOSTNAME }}
  port:
    targetPort: web-port
  tls:
{% if k8s_lb_protocol == 'https' %}
    termination: passthrough
{% else %}
    termination: edge
{% endif %}
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: web-svc
    weight: 100
  wildcardPolicy: None
# IN OCP, CAN NOT HAVE 2 ROUTES TO DIFFERENT SERVICES WITH SAME HOSTNAME
# ---
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   name: parser-route
#   namespace: {{ LEDGER_NAMESPACE }}
# spec:
#   host: {{ LEDGER_HOSTNAME }}
#   port:
#     targetPort: parser-port
#   tls:
# {% if k8s_lb_protocol == 'https' %}
#     termination: passthrough
# {% else %}
#     termination: edge
# {% endif %}
#     insecureEdgeTerminationPolicy: Redirect
#   to:
#     kind: Service
#     name: parser
#     weight: 100
#   wildcardPolicy: None
{% if LEDGER_DB_HOST == "db" %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mysql-data
  name: mysql-data
  namespace: {{ LEDGER_NAMESPACE }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ LEDGER_PVC_STORAGE_CLASS | default(omit, true) }}
  resources:
    requests:
      storage: {{ LEDGER_PVC_SIZE_GB }}Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db
  name: db
  namespace: {{ LEDGER_NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/ledger-default: "true"
        io.kompose.service: db
    spec:
      serviceAccountName: {{ ledger_service_account_name }}
      containers:
      - env:
        - name: ADMIN_USER
          value: admin
        - name: MYSQL_LEDGER_PASSWORD
          value: /run/secrets/db-ledger-password
        - name: admin-password
          value: /run/secrets/admin-password
{% if k8s_container_registry %}
        image: {{ k8s_container_registry | default("ghcr.io/ctrliq/ascender-ledger", true)  ~ "/ledger-db" }}:{{ LEDGER_VERSION }}
{% else %}
        image: {{ LEDGER_DB_IMAGE }}:{{ LEDGER_VERSION }}
{% endif %}
        imagePullPolicy: {{ ascender_image_pull_policy | default("Always") }}
        name: db
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /run/secrets/db-ledger-password
          name: db-ledger-password
        - mountPath: /run/secrets/admin-password
          name: admin-password
        - mountPath: /run/secrets/db-settings
          name: db-settings
        - mountPath: /var/lib/mysql
          name: mysql-data
{% if LEDGER_REGISTRY is defined %}
      imagePullSecrets:
      - name: ledger-registry-secret
{% endif %}
      restartPolicy: Always
      volumes:
      - name: db-ledger-password
        secret:
          items:
          - key: db-ledger-password
            path: db-ledger-password
          secretName: db-ledger-password
      - name: admin-password
        secret:
          items:
          - key: admin-password
            path: admin-password
          secretName: admin-password
      - name: db-settings
        secret:
          items:
          - key: config.json
            path: config.json
          secretName: db-settings
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
{% endif %}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: parser
  name: parser
  namespace: {{ LEDGER_NAMESPACE }}
spec:
  replicas: {{ ledger_parser_replicas }}
  selector:
    matchLabels:
      io.kompose.service: parser
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/ledger-default: "true"
        io.kompose.service: parser
    spec:
      serviceAccountName: {{ ledger_service_account_name }}
      containers:
      - env:
        - name: MYSQL_LEDGER_PASSWORD
          value: /run/secrets/db-ledger-password
{% if k8s_container_registry %}
        image: {{ k8s_container_registry | default("ghcr.io/ctrliq/ascender-ledger", true)  ~ "/ledger-parser" }}:{{ LEDGER_VERSION }}
{% else %}
        image: {{ LEDGER_PARSER_IMAGE }}:{{ LEDGER_VERSION }}
{% endif %}
        imagePullPolicy: {{ ascender_image_pull_policy | default("Always") }}
        name: parser
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /run/secrets/db-ledger-password
          name: db-ledger-password
        - mountPath: /run/secrets/admin-password
          name: admin-password
        - mountPath: /run/secrets/db-settings
          name: db-settings
{% if LEDGER_REGISTRY is defined %}
      imagePullSecrets:
      - name: ledger-registry-secret
{% endif %}
      restartPolicy: Always
      volumes:
      - name: db-ledger-password
        secret:
          items:
          - key: db-ledger-password
            path: db-ledger-password
          secretName: db-ledger-password
      - name: admin-password
        secret:
          items:
          - key: admin-password
            path: admin-password
          secretName: admin-password
      - name: db-settings
        secret:
          items:
          - key: config.json
            path: config.json
          secretName: db-settings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web
  name: web
  namespace: {{ LEDGER_NAMESPACE }}
spec:
  replicas: {{ ledger_web_replicas }}
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/ledger-default: "true"
        io.kompose.service: web
    spec:
      serviceAccountName: {{ ledger_service_account_name }}
      containers:
      - env:
        - name: MYSQL_LEDGER_PASSWORD
          value: /run/secrets/db-ledger-password
{% if k8s_container_registry %}
        image: {{ k8s_container_registry | default("ghcr.io/ctrliq/ascender-ledger", true)  ~ "/ledger-web" }}:{{ LEDGER_VERSION }}
{% else %}
        image: {{ LEDGER_WEB_IMAGE }}:{{ LEDGER_VERSION }}
{% endif %}
        imagePullPolicy: {{ ascender_image_pull_policy | default("Always") }}
        name: web
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /run/secrets/db-ledger-password
          name: db-ledger-password
        - mountPath: /run/secrets/admin-password
          name: admin-password
        - mountPath: /run/secrets/db-settings
          name: db-settings
{% if LEDGER_REGISTRY is defined %}
      imagePullSecrets:
      - name: ledger-registry-secret
{% endif %}
      restartPolicy: Always
      volumes:
      - name: db-ledger-password
        secret:
          items:
          - key: db-ledger-password
            path: db-ledger-password
          secretName: db-ledger-password
      - name: admin-password
        secret:
          items:
          - key: admin-password
            path: admin-password
          secretName: admin-password
      - name: db-settings
        secret:
          items:
          - key: config.json
            path: config.json
          secretName: db-settings
